---

- name: Install MariaDB Client/Server
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "mariadb-server"

- name: Check for existing datadir
  stat: 
    path: "{{ mysqld_datadir }}"
  register: mysqld_datadir_stat
- set_fact:
    mysqld_existing_datadir: yes
  when: mysqld_datadir != mysqld_default_datadir and mysqld_datadir_stat.stat.exists

- name: create mysqld datadir
  file:
    path: "{{ mysqld_datadir }}"
    state: directory
    owner: mysql
    group: mysql
    mode: 0755
  when: not mysqld_datadir_stat.stat.exists

- name: Check for existing tmpdir
  stat: 
    path: "{{ mysqld_tmpdir }}"
  register: mysqld_tmpdir_stat

- name: create mysqld tmpdir
  file:
    path: "{{ mysqld_tmpdir }}"
    state: directory
    owner: mysql
    group: mysql
    mode: 0775
  when: mysqld_create_tmpdir or not mysqld_tmpdir_stat.stat.exists

- name: configure mysqld
  template:
    src: mariadb-server.cnf
    dest: /etc/my.cnf.d/mariadb-server.cnf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart mysql

- name: create mysqld log file
  file:
    path: /var/log/mysqld.log
    state: touch
    owner: mysql
    group: mysql
    mode: 0640
    modification_time: preserve
    access_time: preserve
  when: mysqld_create_mysqld_log

- name: Check for existing log dir
  stat: 
    path: "{{ mysqld_log_dir }}"
  register: mysqld_log_dir_stat

- name: create mysqld tmpdir
  file:
    path: "{{ mysqld_log_dir }}"
    state: directory
    owner: mysql
    group: mysql
    mode: 0775
  when: not mysqld_log_dir_stat.stat.exists

- name: start mariadb service
  service:
    name: "{{ mysqld_service_name }}"
    state: started
    enabled: yes

- import_tasks: root_user_setup.yml
- import_tasks: user_check.yml
