---
- name: CentOS 8 Transition to Vault repositories
  hosts: all
  become: true

  vars_files:
    - ./devenv_vars.default.yml
    - ./devenv_vars.config.yml

  tasks:
    - name: Check if it is CentOS or Rocky
      stat:
        path: /etc/yum.repos.d/CentOS-Linux-BaseOS.repo
      register: centos_base_repo

    - name: Check if vault.centos.org is already used
      shell: grep -E '^baseurl=https:\/\/vault.centos.org' /etc/yum.repos.d/CentOS-Linux-* |wc -l
      register: centos_vault_repo
      changed_when: false
      when:
        - centos_base_repo.stat.exists

    - name: Check if vault.epel.cloud is already used
      shell: grep -E '^baseurl=https:\/\/vault.epel.cloud' /etc/yum.repos.d/CentOS-Linux-* |wc -l
      register: centos_vaultepel_repo
      changed_when: false
      when:
        - centos_base_repo.stat.exists

    - name: Replace outdated CentOS 8 repositories with http://vault.epel.cloud
      shell: sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-* && sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=https://vault.epel.cloud|g" /etc/yum.repos.d/CentOS-*
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version >= '8'
        - centos_base_repo.stat.exists
        - (centos_vaultepel_repo.stdout|int == 0)

    - name: Replace https://vault.centos.org CentOS 8 repositories with http://vault.epel.cloud
      shell: sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-* && sed -i -e "s|#baseurl=https://vault.centos.org|baseurl=https://vault.epel.cloud|g" /etc/yum.repos.d/CentOS-*
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version >= '8'
        - centos_base_repo.stat.exists
        - (centos_vault_repo.stdout|int > 0)
