---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: devenv-centos8-latest
    image: geerlingguy/docker-centos8-ansible:latest
    command: /sbin/init
    privileged: true
    cgroupns: host
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  options:
    D: True
verifier:
  name: testinfra
#lint: |
#  set -e
#  yamllint .
#  ansible-lint
scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
